# Changes here will be overwritten by Copier
_commit: 3.1.0
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: diamhighlvlapps@diamond.ac.uk
author_name: Phil Smith
component_lifecycle: production
component_owner: group:default/high-level-apps
component_type: service
description: Generate storage ring response matrix by kicking individual corrector
    magnets and reading bpm data.
distribution_name: dls-response-matrix
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: dls_response_matrix
pypi: true
repo_name: dls-response-matrix
type_checker: mypy
